"""
Comando: nexus server [setup|start|stop|restart|status]

Configura y controla el servidor de producción.
"""
import os
import subprocess
import sys
from pathlib import Path

import click
from rich.console import Console
from rich.panel import Panel

console = Console()

NGINX_TEMPLATE = """# nginx config for ERP Nexus — {domain}
# Generated by: nexus server setup

upstream erp_nexus {{
    server 127.0.0.1:{port};
}}

server {{
    listen 80;
    server_name {domain};
    return 301 https://$host$request_uri;
}}

server {{
    listen 443 ssl http2;
    server_name {domain};

    ssl_certificate /etc/letsencrypt/live/{domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;

    client_max_body_size 50M;

    location /static/ {{
        alias {static_root}/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }}

    location /media/ {{
        alias {media_root}/;
        expires 7d;
    }}

    location / {{
        proxy_pass http://erp_nexus;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }}
}}
"""

GUNICORN_TEMPLATE = """# gunicorn config for ERP Nexus
# Generated by: nexus server setup

import multiprocessing

bind = "127.0.0.1:{port}"
workers = {workers}
worker_class = "uvicorn.workers.UvicornWorker"
accesslog = "{log_dir}/access.log"
errorlog = "{log_dir}/error.log"
loglevel = "info"
timeout = 120
graceful_timeout = 30
"""

SYSTEMD_TEMPLATE = """# /etc/systemd/system/{service_name}.service
# Generated by: nexus server setup

[Unit]
Description=ERP Nexus — {project_name}
After=network.target postgresql.service redis.service

[Service]
Type=notify
User={user}
Group={group}
WorkingDirectory={project_dir}
Environment="DJANGO_SETTINGS_MODULE=erp_nexus.settings.production"
EnvironmentFile={project_dir}/.env
ExecStart={venv_dir}/bin/gunicorn erp_nexus.asgi:application -c {project_dir}/gunicorn.conf.py
ExecReload=/bin/kill -s HUP $MAINPID
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
"""


@click.group()
def server():
    """Configura y controla el servidor de producción."""
    pass


@server.command()
@click.option("--env", default="production", help="Environment (production/staging)")
@click.option("--domain", default="localhost", help="Dominio del servidor")
@click.option("--port", default=8000, help="Puerto del servidor")
@click.option("--workers", default=None, type=int, help="Workers de gunicorn (default: CPU*2+1)")
def setup(env: str, domain: str, port: int, workers: int | None):
    """
    Genera configs de servidor (nginx, gunicorn, systemd).

    Ejemplos:

      nexus server setup

      nexus server setup --domain erp.miempresa.com --port 8000
    """
    project_dir = Path.cwd()
    if not (project_dir / "manage.py").exists():
        console.print("[red]✗ No se encontró manage.py — ¿estás en un proyecto ERP Nexus?[/red]")
        sys.exit(1)

    if workers is None:
        workers = os.cpu_count() * 2 + 1

    # Paths
    config_dir = project_dir / "config"
    config_dir.mkdir(exist_ok=True)
    log_dir = project_dir / "logs"
    log_dir.mkdir(exist_ok=True)
    static_root = project_dir / "staticfiles"
    media_root = project_dir / "media"
    venv_dir = project_dir / ".venv"

    console.print(f"⚙️  Configurando servidor ({env})...\n")

    # Gunicorn config
    gunicorn_conf = GUNICORN_TEMPLATE.format(
        port=port,
        workers=workers,
        log_dir=log_dir,
    )
    (project_dir / "gunicorn.conf.py").write_text(gunicorn_conf)
    console.print("   ✅ gunicorn.conf.py")

    # Nginx config
    nginx_conf = NGINX_TEMPLATE.format(
        domain=domain,
        port=port,
        static_root=static_root,
        media_root=media_root,
    )
    (config_dir / "nginx.conf").write_text(nginx_conf)
    console.print(f"   ✅ config/nginx.conf")

    # Systemd service
    user = os.environ.get("USER", "www-data")
    service_name = project_dir.name.replace("-", "_")
    systemd_conf = SYSTEMD_TEMPLATE.format(
        service_name=service_name,
        project_name=project_dir.name,
        user=user,
        group=user,
        project_dir=project_dir,
        venv_dir=venv_dir,
    )
    (config_dir / f"{service_name}.service").write_text(systemd_conf)
    console.print(f"   ✅ config/{service_name}.service")

    console.print(Panel.fit(
        f"[green]✓ Configuración generada[/green]\n\n"
        f"[bold]Archivos:[/bold]\n"
        f"  • gunicorn.conf.py\n"
        f"  • config/nginx.conf\n"
        f"  • config/{service_name}.service\n\n"
        f"[bold]Para activar:[/bold]\n"
        f"  1. sudo cp config/nginx.conf /etc/nginx/sites-available/{project_dir.name}\n"
        f"  2. sudo ln -s /etc/nginx/sites-available/{project_dir.name} /etc/nginx/sites-enabled/\n"
        f"  3. sudo cp config/{service_name}.service /etc/systemd/system/\n"
        f"  4. sudo systemctl daemon-reload\n"
        f"  5. sudo systemctl enable {service_name}\n"
        f"  6. nexus server start",
        title="🛠️ Servidor Configurado",
        border_style="green",
    ))


@server.command()
@click.option("--foreground", "-f", is_flag=True, help="Ejecutar en foreground")
def start(foreground: bool):
    """Arranca el servidor con gunicorn."""
    project_dir = Path.cwd()

    if not (project_dir / "gunicorn.conf.py").exists():
        console.print("[yellow]⚠ gunicorn.conf.py no encontrado. Ejecuta: nexus server setup[/yellow]")
        sys.exit(1)

    cmd = [
        sys.executable, "-m", "gunicorn",
        "erp_nexus.asgi:application",
        "-c", str(project_dir / "gunicorn.conf.py"),
    ]

    if foreground:
        console.print("🚀 Arrancando servidor (foreground)...")
        subprocess.run(cmd, cwd=str(project_dir))
    else:
        console.print("🚀 Arrancando servidor (background)...")
        subprocess.Popen(cmd, cwd=str(project_dir))
        console.print("[green]✓ Servidor arrancado[/green]")


@server.command()
def stop():
    """Detiene el servidor (envía SIGTERM a gunicorn)."""
    result = subprocess.run(["pkill", "-f", "gunicorn.*erp_nexus"], capture_output=True)
    if result.returncode == 0:
        console.print("[green]✓ Servidor detenido[/green]")
    else:
        console.print("[yellow]⚠ No se encontró proceso gunicorn corriendo[/yellow]")


@server.command()
def restart():
    """Reinicia el servidor."""
    console.print("🔄 Reiniciando servidor...")
    subprocess.run(["pkill", "-f", "gunicorn.*erp_nexus"], capture_output=True)
    import time
    time.sleep(1)

    project_dir = Path.cwd()
    cmd = [
        sys.executable, "-m", "gunicorn",
        "erp_nexus.asgi:application",
        "-c", str(project_dir / "gunicorn.conf.py"),
    ]
    subprocess.Popen(cmd, cwd=str(project_dir))
    console.print("[green]✓ Servidor reiniciado[/green]")


@server.command()
def status():
    """Verifica el estado del servidor."""
    result = subprocess.run(
        ["pgrep", "-f", "gunicorn.*erp_nexus"],
        capture_output=True, text=True,
    )
    if result.returncode == 0:
        pids = result.stdout.strip().split("\n")
        console.print(f"[green]✓ Servidor corriendo ({len(pids)} procesos)[/green]")
        for pid in pids:
            console.print(f"   PID: {pid}")
    else:
        console.print("[yellow]⚠ Servidor no está corriendo[/yellow]")
